apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: test
  annotations:
    hmcts.github.com/prod-automated: disabled
spec:
  filterTags:
    pattern: '^8'
    extract: ''
  policy:
    alphabetical:
      order: asc
  imageRepositoryRef:
    name: test
